# Generated by Django 5.0.3 on 2024-05-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='name',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
    ]
