# Generated by Django 5.0.3 on 2024-05-07 10:48

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_bio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
