# Generated by Django 5.0.3 on 2024-05-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_bio_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='image',
        ),
    ]
