# Generated by Django 5.0.3 on 2024-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('daily_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weekly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rental_period', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
