# Generated by Django 5.0.3 on 2024-05-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rentalitem_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='upload_date',
        ),
    ]
