# Generated by Django 5.0.3 on 2024-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_rentalitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
