# Generated by Django 5.0.3 on 2024-05-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_rentalitem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
