# Generated by Django 5.0.3 on 2024-05-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_rentalitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rental_item_images/'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='market_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
