# Generated by Django 5.0.6 on 2024-05-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='stars',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
