# Generated by Django 5.0.6 on 2024-05-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_rating_stars_rating_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rating',
        ),
    ]
