# Generated by Django 5.0.3 on 2024-05-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_rentalitem_image_alter_rentalitem_market_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='image',
        ),
    ]
