# Generated by Django 5.0.3 on 2024-05-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_rentalitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='market_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='rental_period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='weekly_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
