# Generated by Django 5.0.3 on 2024-05-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_rentalitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
