# Generated by Django 5.0.3 on 2024-05-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=70)),
                ('daily', models.IntegerField()),
                ('weekly', models.IntegerField()),
                ('monthly', models.IntegerField()),
                ('market_value', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('mini_rental_days', models.IntegerField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
